export const PRODUCT_LIST_REQUEST = "PRODUCT_LIST_REQUEST";
export const PRODUCT_LIST_SUCCESS = "PRODUCT_LIST_SUCCESS";
export const PRODUCT_LIST_FAIL = "PRODUCT_LIST_FAIL";

export const SELECTED_PRODUCT_REQUEST = "SELECTED_PRODUCT_REQUEST";
export const SELECTED_PRODUCT_SUCCESS = "SELECTED_PRODUCT_SUCCESS";
export const SELECTED_PRODUCT_FAIL = "SELECTED_PRODUCT_FAIL";
